package com.crone.skillbranchtest.data.storage.models;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.crone.skillbranchtest.data.storage.models.Houses;
import com.crone.skillbranchtest.data.storage.models.Persons;
import com.crone.skillbranchtest.data.storage.models.Titles;

import com.crone.skillbranchtest.data.storage.models.HousesDao;
import com.crone.skillbranchtest.data.storage.models.PersonsDao;
import com.crone.skillbranchtest.data.storage.models.TitlesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig housesDaoConfig;
    private final DaoConfig personsDaoConfig;
    private final DaoConfig titlesDaoConfig;

    private final HousesDao housesDao;
    private final PersonsDao personsDao;
    private final TitlesDao titlesDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        housesDaoConfig = daoConfigMap.get(HousesDao.class).clone();
        housesDaoConfig.initIdentityScope(type);

        personsDaoConfig = daoConfigMap.get(PersonsDao.class).clone();
        personsDaoConfig.initIdentityScope(type);

        titlesDaoConfig = daoConfigMap.get(TitlesDao.class).clone();
        titlesDaoConfig.initIdentityScope(type);

        housesDao = new HousesDao(housesDaoConfig, this);
        personsDao = new PersonsDao(personsDaoConfig, this);
        titlesDao = new TitlesDao(titlesDaoConfig, this);

        registerDao(Houses.class, housesDao);
        registerDao(Persons.class, personsDao);
        registerDao(Titles.class, titlesDao);
    }
    
    public void clear() {
        housesDaoConfig.clearIdentityScope();
        personsDaoConfig.clearIdentityScope();
        titlesDaoConfig.clearIdentityScope();
    }

    public HousesDao getHousesDao() {
        return housesDao;
    }

    public PersonsDao getPersonsDao() {
        return personsDao;
    }

    public TitlesDao getTitlesDao() {
        return titlesDao;
    }

}
